mod ast_provenance;
pub mod conditions;
pub mod core;
mod dataflow;
mod flow_tracker;
pub mod modes;
mod multifile_taint;
mod output;
mod parser_helper;
pub mod prefilter;
mod scan_context;
mod scanning_logic;
mod taint_utils;
pub mod utils;
mod vulnerability_scanner;

pub use crate::models::Finding;
pub use core::{ScanningLogic, VulnerabilityScanner};
pub use modes::{run_auto_detection_scan, run_explicit_scan, run_taint_analysis};
pub use prefilter::{FilterStats, PreFilter};
